### ISSUE TITLE
License version

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ujson-feedstock#1]
Please specify in `meta.yaml` the type of BSD license used (e.g. BSD 3-Clause for the 3 clause BSD license) and please re-render to get this into the README of the feedstock. Thanks.

**Comment by kszucs** [comment]
@jakirkham actually I don't know the type of it.

setup.py [mentions](https://github.com/esnme/ultrajson/blob/master/setup.py#L98) BSD
the [LICENSE](https://github.com/esnme/ultrajson/blob/master/LICENSE.txt) file seems custom

**Comment by dougalsutherland** [comment]
That's 3-clause: compare to [this](https://opensource.org/licenses/BSD-3-Clause).
